name: Android Builds

on: push

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Builds Project
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test